### ISSUE TITLE
time.clock is deprecated in python 3.8

### ISSUE THREAD

**Issue by kennethwsmith** [KBlixt/Movie-Extra-Downloader#10]
I might have a configuration problem, but I believe time.clock is deprecated in Python 3.8

```
File "/home/home/Movie-Extra-Downloader-master/url_finders.py", line 3, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Comment by KBlixt** [comment]
I have only verified the script for 3.5 and 3.6. Use one of those to run the script. I might maintain other version for it eventually.

**Comment by KBlixt** [comment]
this is now fixed
