### ISSUE TITLE
Thoughts on using youtube-dlc or yt-dlp instead of youtube-dl? -- Also getting frequent vague errors

### ISSUE THREAD

**Issue by Daxiongmao87** [KBlixt/Movie-Extra-Downloader#13]
Edit: Issue on my end with permssions.

**Comment by Daxiongmao87** [comment]
Did a simple search-replace for youtube_dl to yt_dlp.  Still experiencing errors.  I'll provide a list of failed movies when It's done.

**Comment by KBlixt** [comment]
What permission issue did you have? Maybe I could add a more helpful error message if it occurs for others.

I hope the script is working well for you 🙂

**Comment by Daxiongmao87** [comment]
Thanks.  my directory was owned by a different user for my kubernetes setup.  I gave access to my jenkins user so they would be able to create/edit files there.  However I'm still getting a lot of failures, probably around 50% of my library.

**Comment by KBlixt** [comment]
Yeah any youtube download method will always be a bit janky since YouTube change every so often. I'll take a look at it in the week hopefully. What errors do you get?

**Comment by KBlixt** [comment]
if you could post the errors you're getting I could investigate them.

**Comment by Daxiongmao87** [comment]
I don't know how this ended up on another comment, I must have had too many chrome tabs open.  I went ahead and deleted it and put it here.  Sorry about that. 

This is the only error I see:
![image](https://user-images.githubusercontent.com/967432/150621643-159893c8-7e5b-4834-8646-c9b49dbea60d.png)

**Comment by KBlixt** [comment]
Could you update the script and try again. I've added more error information to the message. Stupid past me forgot to put in the actual error.

Sorry for it looking so awful. It have however given me some inspiration to revisit the project.

**Comment by Daxiongmao87** [comment]
Awesome, will do!  No need to apologize, this is a very useful utility that allows me to be less reliant on the internet for extras.  :) I'll report after updating

**Comment by Daxiongmao87** [comment]
The error I'm receiving.
'NoneType' object has no attribute 'replace'

Seems like the object it's trying to grab doesn't exist

**Comment by KBlixt** [comment]
mh, ok. that could be anywhere. I've added more info about the issue, could you try update and run again?

**Comment by Daxiongmao87** [comment]
After a git pull, Still same error unfortunately.  

![Screenshot_20220123-112025](https://user-images.githubusercontent.com/967432/150690137-6cbe789d-454d-481d-9d8d-d3cd6967ef0c.png)

**Comment by KBlixt** [comment]
aright, I messed up 😬. try again ...

**Comment by Daxiongmao87** [comment]
No worries!

`'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "Movie-Extra-Downloader.py", line 160, in handle_library
    handle_directory(os.path.join(library, folder))
  File "Movie-Extra-Downloader.py", line 45, in handle_directory
    extra_config = ExtraSettings(os.path.join(configs, config))
  File "/home/jenkins/workspace/Download Plex Extras/Movie-Extra-Downloader/extra_config.py", line 38, in __init__
    tools.make_list_from_string(self.config['PRIORITY_RULES'].get('preferred_channels').replace('\n', ''))
AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by KBlixt** [comment]
Alright, I think I sorted this one out. Let me know if you still get these errors and I'll keep wacking them till they're gone!

Thanks for providing me with these issues, really appreciate it.

**Comment by Daxiongmao87** [comment]
thank you i'll give it a test when I get home after work!

**Comment by Daxiongmao87** [comment]
It seems to be downloading now without a hitch! Awesome. I looked at the latest commit, looks like a missing parameter was causing the issue?  Thanks again!

**Comment by KBlixt** [comment]
Good to hear 😁

Yeah it's a optional parameter which I usually don't need but I needed in this case.

Have a good one 🙂
