### ISSUE TITLE
Trailer Language

### ISSUE THREAD

**Issue by Secarius** [KBlixt/Movie-Extra-Downloader#14]
Hi @KBlixt is it possible to try to download only Trailes with german Language?

**Comment by Secarius** [comment]
Did find a way :)

**Comment by KBlixt** [comment]
Nice 😁
How did you do it?

Tbh, I don't think I could have helped you. It was such a long time I had a look at this 😅
I really want to take another take at this since I made this fairly early in my python learning experience.

Hope the script brings you joy 🙂

**Comment by Secarius** [comment]
![image](https://user-images.githubusercontent.com/777486/165493456-44ebeefd-289a-4370-8903-207c22baad34.png)
