### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: './records/'

### ISSUE THREAD

**Issue by UnR34L** [KBlixt/Movie-Extra-Downloader#2]
It ran once, got the wrong movie, then never ran again.

Command:
> root@Jail|plex:/root/Movie-Extra-Downloader# python3.6 ./Movie-Extra-Downloader.py -d /mnt/storage1/mymedia/test/Die\ Hard\ \(1988\)/

Output:
> Downloading tmdb movie search page.
> Traceback (most recent call last):
>   File "./Movie-Extra-Downloader.py", line 109, in <module>
>     handle_directory(args.directory)
>   File "./Movie-Extra-Downloader.py", line 27, in handle_directory
>     directory = Directory.load_directory(os.path.join(records, os.path.split(folder)[1]))
>   File "/root/Movie-Extra-Downloader/directory.py", line 40, in load_directory
>     with open(file, 'r') as load_file:
> IsADirectoryError: [Errno 21] Is a directory: './records/'

FreeBSD: 11.2-RELEASE

Installed modules:
> root@Jail|plex:/root/Movie-Extra-Downloader# pip list
> Package                  Version
> beautifulsoup4           4.6.1
> cachetools               2.1.0
> certifi                  2018.4.16
> chardet                  3.0.4
> google                   2.0.1
> google-api-python-client 1.7.4
> google-auth              1.5.1
> google-auth-httplib2     0.0.3
> httplib2                 0.11.3
> idna                     2.7
> kwconfig                 1.1.7
> pip                      18.0
> pyasn1                   0.4.4
> pyasn1-modules           0.2.2
> pytz                     2018.5
> requests                 2.19.1
> rsa                      3.4.2
> setuptools               39.2.0
> six                      1.11.0
> uritemplate              3.0.0
> urllib3                  1.23
> youtube-dl               2018.8.4

**Comment by UnR34L** [comment]
Just tried using library instead of directory works fine. So it's only a problem with -d

Command:

> root@Jail|plex:/root/Movie-Extra-Downloader# python3.6 ./Movie-Extra-Downloader.py -l /mnt/storage1/mymedia/test/

I really like this, keep up the good work.

**Comment by KBlixt** [comment]
I'll have a look at this.

Thank you :) and thanks for helping out. :)

**Comment by KBlixt** [comment]
this should be solved now. the issue was that the provided directory ended with a '/'. this should now be resolved so that even if the provided directory do end with a directory divider it will simply ignore it.

**Comment by UnR34L** [comment]
Fixed 😄
