### ISSUE TITLE
[Request] Check if a trailer exists before downloading.

### ISSUE THREAD

**Issue by UnR34L** [KBlixt/Movie-Extra-Downloader#3]
I had a few false positives,

So I have to delete the records before it'll check that movie, I deleted the entire records folder now it's re-downloading thousands of trailers. Yeah, I should have only removed the records of the movies that I wanted fixed, but I didn't know.

Could you have it check if the trailer exists then skip it ?

**Comment by KBlixt** [comment]
Yeah good idea, I'll do that.

**Comment by KBlixt** [comment]
This is now implemented. to enable this functionality you'll need to add this to the trailer configuration in the [EXTRA_CONFIG] section. 
 
"skip_movies_with_existing_trailers = true"

default is set to false as to not break older config files.

yeah, I know it's a ugly name. but it sure is descriptive...

**Comment by KBlixt** [comment]
And please, feel free to name the false positives if you have the time.

**Comment by UnR34L** [comment]
> And please, feel free to name the false positives if you have the time.

Try with "The Man from U.N.C.L.E. (2015)" I ended up with a trailer for "The Man From Nowhere".

I'll have to go through them, if I find them I'll let you know.

**Comment by UnR34L** [comment]
Working 😄 

> yeah, I know it's a ugly name. but it sure is descriptive...

Why not just "skip_existing" ? because you may decide to use it with the experimental.cfg ? 😉

**Comment by KBlixt** [comment]
The Man from U.N.C.L.E (2015) issue have now been resolved. acronyms with dots should now work as expected.
