### ISSUE TITLE
Filter by "Features: HD"

### ISSUE THREAD

**Issue by ghost** [KBlixt/Movie-Extra-Downloader#4]
Is it possible to filter the search results, in the same way that it is possible through the YouTube website, to only show HD videos? 

https://i.imgur.com/TzPa9ch.png

I feel this would provide better results rather than increasing the search limit which can increase the possibility of bad matches.

**Comment by ghost** [comment]
After some more investigating I've found that adding ", hd" (without quotes) to the query field in [SEARCHES] subsection enables this.

Example: query_1 = {movie_original_title} {movie_release_year} trailer, hd

**Comment by KBlixt** [comment]
nice find! this is exactly what I intended this to do :) 

you don't need the comma since the query_# field will be used in the google search/youtube search directly but with the titles and release year filled in.

I will provide a thorough guide of the config options in a while.
