### ISSUE TITLE
Windows troubles

### ISSUE THREAD

**Issue by sivan-koren** [KBlixt/Movie-Extra-Downloader#5]
I think the config files use Unix style '0x0a' line breaks. I'm just guessing, but this might be unsuitable for Windows users. For me, this seems to have caused it to fail to use the API key. Again just a guess. Adding some line breaks in the config file allowed me to sort of continue.

Now I get no errors but the script doesn't seem to do much.

"Downloading tmdb search page."

Then exits...

**Comment by KBlixt** [comment]
sorry for not seeing this earlier, haven't been active for a while. 

strange, Most of my coding is done on a windows machine and it works great there except that I haven't bothered installing ffmpeg.

maybe if you give me more specifics I could help you out, like what arguments do you use and your general file structure of your library.

**Comment by sivan-koren** [comment]
I can't remember what I was doing with this. Sorry I can't be of more help.
