### ISSUE TITLE
-bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by sasagr** [KBlixt/Movie-Extra-Downloader#7]
Hi, I have no idea why I m getting this

pi@raspberrypi:~/Movie-Extra-Downloader $ python3 Movie-Extra-Downloader.py -d /mnt/GD/Movies/A Rainy Day in New York (2019)
-bash: syntax error near unexpected token `('

**Comment by sasagr** [comment]
I m not sure what I did but now it is working.. maybe because the year is 2020 and not 2019

**Comment by sasagr** [comment]
sorry but I have to reopen the issue. This is happening with -d argument. With -l argument I have on issue. I m running the code on a raspberry with debian.
Maybe there is some incompatibility?

**Comment by KBlixt** [comment]
If you run it against a specific movie (the -d mode) you'll need to pass the directory without spaces. Either escape them with foreslash or put quotes around the entire argument. That should solve the issue.
