### ISSUE TITLE
directory.py - TMDB error

### ISSUE THREAD

**Issue by unintended-consequences** [KBlixt/Movie-Extra-Downloader#9]
Seems like an edge case:

Code breaks when TMDB match returns is more than +/- 1 year of release date.

Example: Need for Speed (2014)

TMDB look up returns Need for Speed (2018)

directory.py - Line 126 only accepts movie_release_year + / - 1 so you get a KeyError: 'release_date'

You can bypass this error by removing the TMDB key (quick fix) from default_config

**Comment by unintended-consequences** [comment]
Also failed for Onward (2020)

**Comment by KBlixt** [comment]
I'll investigate.

**Comment by KBlixt** [comment]
I'm not getting this error. I might have fixed it while fixing other similar issues, please confirm the fix.
